export const mockCustomerDetails = {
  customerId: '6218587',
  globalCustomerId: 'D11811E5-F683-0965-E053-A11CFA0A781A',
  firstName: 'Paul',
  lastName: 'Watson',
  middleInitial: null,
  coworker: 'N',
  suffix: null,
  salutation: null,
  taxId: '630788375',
  taxIdType: 'SSN',
  governmentId: '0903662925',
  mdmId: '53116733',
  oktaId: null,
  oktaCreatedDate: null,
  governmentIdType: 'DL',
  dateOfBirth: '1898-08-27',
  governmentIdIssuedState: 'TX',
  emailAddress: 'pwatson49erfan@xxxxx.com',
  preferredContactMethod: 'PH',
  preferredLanguage: 'ENG',
  printReceiptMethod: 'PRNT',
  monthlyMortgagePayment: '0',
  mortgageCompanyName: null,
  residenceSince: '2018-05-04',
  phoneSolicitationAllowed: 'N',
  emailSolicitationAllowed: 'Y',
  mailSolicitationAllowed: 'Y',
  textSolicitationAllowed: 'Y',
  paymentReminderCallsAllowed: 'N',
  remotePaymentAllowed: 'N',
  acceptCheck: 'N',
  verified: 'N',
  deDecisionId: '1439576845271564',
  deExceptionReason: null,
  salesLeadId: null,
  verifiedDate: '2021-07-23T00:00:00.000Z',
  createdBy: '189764',
  lastModifiedBy: '848008',
  createdDate: '2021-10-08T19:30:14.000Z',
  lastModifiedDate: '2022-02-10T10:10:22.072Z',
  createdSource: 'ENTERPRISE',
  lastModifiedSource: 'RACDB',
  activeAgreements: '1',
  inActiveAgreements: '1',
  pifAgreements: '0',
  epoAgreements: '1',
  coCustomer: 'N',
  coCustomerId: 12,
  phones: [
    {
      phoneId: '1800048184',
      phoneNumber: '5555578999',
      phoneType: 'CELL',
      extension: '',
      primary: 'N',
      callTimeType: 'EVEN',
      note: '',
    },
    {
      phoneId: '13118302',
      phoneNumber: '4698354602',
      phoneType: 'CELL',
      extension: null,
      primary: 'Y',
      callTimeType: 'EVEN',
      note: "Jill's phone ",
    },
  ],
  addresses: [
    {
      addressId: '8723636',
      addressType: 'MAIL',
      addressLine1: '3601 FRED WILSON AVE',
      addressLine2: '',
      city: 'EL PASO',
      state: 'TX',
      postalCode: '79904-6037',
      latitude: null,
      longitude: null,
      verifiedDate: '2021-07-21T00:00:00.000Z',
    },
    {
      addressId: '8723635',
      addressType: 'PRIM',
      addressLine1: '3601 FRED WILSON AVE',
      addressLine2: '',
      city: 'EL PASO',
      state: 'TX',
      postalCode: '79904-6037',
      latitude: null,
      longitude: null,
      verifiedDate: '2021-07-21T00:00:00.000Z',
    },
  ],
  personalReferences: [
    {
      personalReferenceId: '1800023110',
      firstName: 'hhh',
      lastName: 'fff',
      relationshipType: 'REL',
      relationLengthYears: 'NaN',
      phoneNumber: '4364575676',
      bestTimeToCall: 'AFTN',
      verifiedDate: null,
      active: 'Y',
      doNotCall: 'N',
      addressLine1: 'hhh',
      addressLine2: '',
      city: 'ggg',
      state: 'VA',
      postalCode: '20109',
    },
  ],
  employerReferences: [
    {
      employerReferenceId: '8265091',
      employerName: 'VA/SSI',
      takeHomePay: '0',
      supervisorFirstName: '',
      supervisorLastName: '',
      jobTitle: '',
      employerPhoneNumber: '7066814279',
      employerPhoneExtension: null,
      addressLine1: 'ss',
      addressLine2: null,
      city: 'crf',
      state: 'AE',
      postalCode: '34534-3445',
      doNotVisit: 'N',
      doNotCall: 'N',
      employmentBeginDate: '2001-10-18',
      workStartTime: null,
      workEndTime: null,
      employerPayschedule: 'MON',
      lengthOfEmploymentYears: '0',
      daysPaid: '1',
      employmentEndDate: null,
      verifiedDate: null,
      active: 'Y',
    },
  ],
  customerRoutes: [
    {
      customerRouteId: '6738549',
      storeRouteId: '4266',
      storeId: '848',
      storeNumber: '00848',
      routeCode: 'M',
    },
  ],
  customerSinceDate: '2018-05-04',
};
